name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer (X.Y.Z)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token:    ${{ secrets.GITHUB_TOKEN }}
          skip-commit:     'true'
          skip-tag:        'true'
          skip-version-file: 'true'
          output-file:     'false'
          release-count:   '1'
          tag-prefix:      'v'

      - name: Zip up repo
        run: |
          zip -r WeaponMechanicsResourcePack-${{ github.event.inputs.version }}.zip . \
            -x ".git/*" ".github/*" ".*"

      - name: Create GitHub Release & upload asset
        uses: softprops/action-gh-release@v2
        with:
          token:    ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.event.inputs.version }}
          name:     v${{ github.event.inputs.version }}
          body:     ${{ steps.changelog.outputs.clean_changelog }}
          files: |
            WeaponMechanicsResourcePack-${{ github.event.inputs.version }}.zip
