name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer (X.Y.Z)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          # don’t bump/tag/commit—just output the changelog
          skip-commit: 'true'
          skip-tag: 'true'
          skip-version-file: 'true'
          output-file: 'false'
          # only diff since the latest tag
          release-count: '1'
          # if your tags are prefixed with “v”
          tag-prefix: 'v'

      - name: Package repo
        run: |
          zip -r WeaponMechanicsResourcePack-${{ github.event.inputs.version }}.zip . \
            -x ".git/*" ".github/*" ".*"

      - name: Create GitHub Release
        id: create_rel
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_rel.outputs.upload_url }}
          asset_path: WeaponMechanicsResourcePack-${{ github.event.inputs.version }}.zip
          asset_name: WeaponMechanicsResourcePack-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip
